export const FETCH_EXAMPLE = 'FETCH_EXAMPLE';
export const SEARCH_EXAMPLE = 'SEARCH_EXAMPLE';
export const FILTER_EXAMPLE = 'FILTER_EXAMPLE';
export const ADD_EXAMPLE = 'ADD_EXAMPLE';
export const UPDATE_EXAMPLE = 'UPDATE_EXAMPLE';
export const DELETE_EXAMPLE = 'DELETE_EXAMPLE';
export const EDIT_EXAMPLE = 'EDIT_EXAMPLE';
